name: Ext. PR tests & int. branches pushes

# for external contribution pull requests,
#  and internal pushes to specific branches (!= dev)

on:
  pull_request:
    branches-ignore:
      - "master"
    paths-ignore: # not always respected. See https://github.com/actions/runner/issues/2324#issuecomment-1703345084
      - ".github/**"
      - "**.md"
  push:
    branches-ignore:
      - "dev"
      - "master"
    paths-ignore:
      - ".github/**"
      - "**.md"

# todo add whitelist paths like entrypoint_nightly.yml

# creating a separate concurrency group for each PR
# so that our "PR checks" are always running for the latest commit in the PR
# and as PRs are updated we want to make sure "in progress" jobs are killed so we don't waste resources
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true


jobs:
  test:
    name: Python tests and checks
    uses: ./.github/workflows/sub_testing.yml

  build:
    name: Build Python 🐍 distributions
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@main
        with:
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install requirements
        run: python -m pip install --user build virtualenv setuptools
      - name: Cleaning
        run : python setup.py clean
      - name: Build Exegol
        run: python -m build --sdist --outdir dist/ .
      - name: Create testing venv
        run: python -m venv vtest
      - name: Install pip package locally
        run: ./vtest/bin/pip install ./dist/*
